terraform {
  required_providers {
    dokploy = {
      source = "pompydev/dokploy"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "4.0.5"
    }
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

# Configure the Provider
provider "dokploy" {
  host    = var.host
  api_key = var.api_key
}

provider "github" {
  token = var.github_token
  owner = var.github_owner
}

# Create a Project
resource "dokploy_project" "main" {
  name        = "Production Project"
  description = "Main infrastructure"
}

# Create an Environment within the Project
resource "dokploy_environment" "staging" {
  name        = "staging"
  project_id  = dokploy_project.main.id
  description = "staging environment for testing"
}

# Deploy a Database
resource "dokploy_database" "postgres" {
  name           = "main-db"
  type           = "postgres"
  password       = var.db_password
  project_id     = dokploy_project.main.id
  environment_id = dokploy_environment.staging.id
  version        = "15"
}

# Generate an SSH Key automatically
resource "tls_private_key" "pk" {
  algorithm = "ED25519"
}

resource "dokploy_ssh_key" "generated" {
  name        = "terraform-generated-key"
  description = "Key generated by Terraform for private repos"
  private_key = tls_private_key.pk.private_key_openssh
  public_key  = tls_private_key.pk.public_key_openssh
}

# Add Deploy Key to GitHub Repository
resource "github_repository_deploy_key" "app_key" {
  repository = "hello-aws"
  title      = "dokploy-deploy-key"
  key        = tls_private_key.pk.public_key_openssh
  read_only  = true
}

# Deploy an Application (Private Repo)
resource "dokploy_application" "web_app" {
  name           = "web-frontend"
  project_id     = dokploy_project.main.id
  environment_id = dokploy_environment.staging.id
  # Use Custom Git settings for private repo via SSH
  custom_git_url        = var.custom_git_url
  custom_git_branch     = "main"
  custom_git_ssh_key_id = dokploy_ssh_key.generated.id
  build_type            = "dockerfile"
  dockerfile_path       = "./Dockerfile"
  auto_deploy           = true
  deploy_on_create      = true

  # Ensure key is added to GitHub before deploying app
  depends_on = [github_repository_deploy_key.app_key]
}

# Configure a Domain for the Application
resource "dokploy_domain" "app_domain" {
  application_id      = dokploy_application.web_app.id
  generate_traefik_me = true
  path                = "/"
  port                = 3000
  https               = false
  redeploy_on_update  = true
}

# Deploy an Application using GitHub Provider
resource "dokploy_application" "github_app" {
  name           = "github-app"
  project_id     = dokploy_project.main.id
  environment_id = dokploy_environment.staging.id

  # GitHub Provider settings
  github_id          = var.github_app_id
  github_owner       = var.github_owner
  github_repository  = var.github_repository
  github_branch      = "main"
  github_build_path  = "./"
  enable_submodules  = false
  trigger_type       = "tag"
  github_watch_paths = ["src/**", "package.json"]

  build_type       = "dockerfile"
  auto_deploy      = true
  deploy_on_create = false
}

# Configure a Domain for the GitHub Application
resource "dokploy_domain" "github_app_domain" {
  application_id      = dokploy_application.github_app.id
  generate_traefik_me = true
  path                = "/"
  port                = 3000
  https               = false
  redeploy_on_update  = true
}

resource "dokploy_environment_variables" "app_vars" {
  application_id = dokploy_application.web_app.id
  variables = {
    "DATABASE_URL" = "postgres://user:${var.db_password}@${dokploy_database.postgres.name}:${dokploy_database.postgres.internal_port}/db"
  }
}

# Deploy a Docker Compose resource
resource "dokploy_compose" "web_app_compose" {
  name                  = "web-app-compose"
  project_id            = dokploy_project.main.id
  environment_id        = dokploy_environment.staging.id
  custom_git_url        = var.custom_git_url
  custom_git_branch     = "main"
  custom_git_ssh_key_id = dokploy_ssh_key.generated.id
  compose_path          = "./docker-compose.yml"
  auto_deploy           = true
  deploy_on_create      = true
}

# Configure a Domain for the Compose Stack
resource "dokploy_domain" "compose_domain" {
  compose_id          = dokploy_compose.web_app_compose.id
  service_name        = var.compose_service_name
  generate_traefik_me = true
  path                = "/"
  port                = 3000
  https               = false
  redeploy_on_update  = true
}

output "generated_domain" {
  value       = dokploy_domain.app_domain.host
  description = "The generated traefik.me domain for the app"
}

output "generated_compose_domain" {
  value       = dokploy_domain.compose_domain.host
  description = "The generated traefik.me domain for the compose stack"
}
