[tools]
"nix:gopls" = "0.22.0"
cspell = "10.0.1"
go = "1.26.4"
golangci-lint = "2.12.2"
prettier = "3.9.4"
terraform = "1.15.7"

# indirect dependencies
node = "26.4.0" # required by npm backend (e.g. prettier)

[plugins]
nix = "https://github.com/jbadeau/mise-nix"

[env]
GOFLAGS = ""

[tasks.verify]
depends = ["fmt", "spell", "lint", "install", "generate"]
alias = "vv"

[tasks.out]
run = "go build -o terraform-provider-dokploy ."
alias = "o"

[tasks.build]
run = "go build -v ./..."

[tasks.install]
depends = ["build"]
run = "go install -v ./..."

[tasks.lint]
run = "golangci-lint run"

[tasks.generate]
dir = "{{config_root}}/tools"
run = "go generate ./..."

[tasks.fmt]
run = '''
gofmt -s -w -e .
prettier --write .
'''

[tasks.spell]
run = "cspell ."

[tasks.test]
run = "go test -v -cover -timeout=120s -parallel=10 ./..."

[tasks.test-acceptance]
env = { TF_ACC = "1" }
run = "go test -v -cover -timeout 120m ./..."
